### ISSUE TITLE
Allow sqltoaster to output YAML

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/sqltoast#104]
Instead of the custom output format that sqltoaster currently emits, I'd like to allow outputting to a YAML document that describes the SQL statements and the components of the parse tree.

It would probably be good to create some custom iomanips for a subclassed std::ostream object that would control things like the output format as well as current indentation level.

The trickiest part of the YAML output is deciding how to represent in YAML the search condition and predicate relationships. The current raw output from the predicate_t and search_condition_t inserters/extractors basically looks like the original SQL, reconstructed with wrappers around the individual elements.

For example, given a SQL statement of:

```sql
SELECT * FROM t1 WHERE t1.a = 1 OR t1.b > 2
```

`<<`'ing the search_condition_t& for the query_specification_t's where_condition to an ostream will result in this:

```
where:
  column-reference[t1.a] = literal[1] OR column-reference[t1.b] > literal[2]
```

however, we want the YAML output to be easier to parse in a machine-readable fashion (as opposed to the human-readable preference of the `<<` inserter's output.

I'm thinking maybe something like this?

```
where:
  - predicate_type: comparison
    op: EQUAL
    left: column-reference[t1.a]
    right: literal[b]
    or:
        - predicate_type: comparison
          op: GREATER_THAN
          left: column-reference[t1.b]
          right: literal[2]
```
